comercializacao/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy
from django.contrib import admin

from . import views

urlpatterns = [

	url(r'^venda_cadastrar/$', views.venda_cadastrar, name='venda_cadastrar'),
	url(r'^venda_listar/$', views.venda_listar, name='venda_listar'),
	url(r'^venda_editar/(?P<lote>[-\w]+)/$', views.venda_editar, name='venda_editar'),
	url(r'^venda_remover/(?P<lote>[-\w]+)/$', views.venda_remover, name='venda_remover'),
	url(r'^venda_fechar_abrir/(?P<lote>[-\w]+)/$',  views.venda_fechar_abrir, name='venda_fechar_abrir'),

	url(r'^ajax_lote_venda/(?P<origem>[\w]+)/(?P<lote>[-\w]+)/$', views.ajax_lote_venda, name='ajax_lote_venda'),

	url(r'^compra_cadastrar/$', views.compra_cadastrar, name='compra_cadastrar'),
	url(r'^compra_listar/$', views.compra_listar, name='compra_listar'),
	url(r'^compra_editar/(?P<lote>[-\w]+)/$', views.compra_editar, name='compra_editar'),
	url(r'^compra_remover/(?P<lote>[-\w]+)/$', views.compra_remover, name='compra_remover'),
	url(r'^compra_fechar_abrir/(?P<lote>[-\w]+)/$',  views.compra_fechar_abrir, name='compra_fechar_abrir'),
]

mapa/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

from . import views

urlpatterns = [

    # url(r'^$', TemplateView.as_view(template_name='mapa.html'), name='mapa'),

    url(r'^$', views.index, name='mapa'),


    url(r'^talhoesglebas.geojson$', views.talhoesglebas, name='talhoesglebas'),
    url(r'^propriedades.geojson$', views.propriedades, name='propriedades'),

]

comercializacao/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.gis.db import models
from django.contrib.auth.models import User
from django import utils
from django.utils import timezone

from cadastro.models import (
    Equipamento,
    Propriedade,
    ClienteFornecedor,
    Produto,
    FilterUserManager,
    )

from ciclo.models import (
	Colheita,
    )

ORIGEM_CHOICES = (
    ('1', 'Própria'),
    ('2', 'Terceiros'),
)

TIPO_UNIDADE_CHOICES = (
    ('1', 'Maço(s)'),
    ('2', 'Unidade(s)'),
    ('3', 'Caixa(s)'),
    ('4', 'Kg'),
    ('5', 'Bandeja(s)'),
    ('6', 'Dúzia(s)'),
    ('7', 'Cento(s)'),
)

STATUS_LOTE_CHOICES = (
    ('1', 'Aberto'),
    ('2', 'Encerrado'),
)

class Compra(models.Model):
	'''Compra'''

	user = models.ForeignKey(User, on_delete=models.CASCADE)
	propriedade = models.ForeignKey(Propriedade, null=True, blank=True, on_delete=models.CASCADE)
	lote = models.IntegerField()
	data_compra = models.DateField()
	fornecedor = models.ForeignKey(ClienteFornecedor, null=True, blank=True, on_delete=models.CASCADE)
	produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
	quantidade = models.FloatField()
	tipo_unidade = models.CharField('Unidade', max_length=1, choices=TIPO_UNIDADE_CHOICES)
	preco_unidade = models.FloatField()
	valor_total = models.FloatField()
	descarte = models.FloatField(blank=True, null=True)
	status_lote = models.CharField('Status do Lote', max_length=1, choices=STATUS_LOTE_CHOICES)
	data_cadastro = models.DateTimeField(blank=True, null=True)

	objects = FilterUserManager()

	def __unicode__(self):
		return unicode(self.lote) + ' / ' + unicode(self.fornecedor) +' / ' + unicode(self.produto) + ' / ' + unicode(self.data_compra)

	class Meta:
		verbose_name = 'Compra'
		verbose_name_plural = 'Compras'


class Venda(models.Model):
	'''Venda'''

	user = models.ForeignKey(User, on_delete=models.CASCADE)
	propriedade = models.ForeignKey(Propriedade, null=True, blank=True, on_delete=models.CASCADE)
	lote = models.IntegerField()
	data_venda = models.DateField()
	cliente = models.ForeignKey(ClienteFornecedor, on_delete=models.CASCADE)
	origem = models.CharField('Origem', max_length=1, choices=ORIGEM_CHOICES)
	lote_colheita = models.ForeignKey(Colheita, null=True, blank=True, on_delete=models.CASCADE)
	lote_compra = models.ForeignKey(Compra, null=True, blank=True, on_delete=models.CASCADE)
	quantidade = models.FloatField()
	preco_unidade = models.FloatField()
	valor_total = models.FloatField()
	status_lote = models.CharField('Status do Lote', max_length=1, choices=STATUS_LOTE_CHOICES)
	data_cadastro = models.DateTimeField(blank=True, null=True)
	
	objects = FilterUserManager()

	def __unicode__(self):
		return unicode(self.id)

	class Meta:
		verbose_name = 'Venda'
		verbose_name_plural = 'Vendas'

comercializacao/forms.py
# -*- coding: utf-8  -*-

from django.forms import inlineformset_factory
from django import forms
from django.contrib.auth.models import User
from django.utils import timezone

from cadastro.models import (
	ClienteFornecedor,
	Produto,
)

from ciclo.models import (
	Colheita,
    )

from comercializacao.models import (
	Venda,
	Compra,
    )

class VendaForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.request_user = kwargs.pop('request_user')
		super(VendaForm, self).__init__(*args, **kwargs)

		self.fields["lote_colheita"].queryset = Colheita.objects.get_queryset_by_user(self.request_user).order_by('-data_colheita')
		self.fields["lote"].initial = ''

	class Meta:
		model = Venda
		fields = '__all__'
		exclude = ['user','propriedade','status_lote']
		widgets = {
			'data_venda': forms.DateInput(attrs={'class': 'date-picker form-control'}),
			'lote': forms.NumberInput(attrs={'class': 'form-control'}),
			'cliente': forms.Select(attrs={'class': 'form-control'}),
			'origem': forms.Select(attrs={'class': 'form-control'}),
			'lote_colheita': forms.Select(attrs={'class': 'form-control'}),
			'lote_compra': forms.Select(attrs={'class': 'form-control'}),
			'quantidade': forms.NumberInput(attrs={'class': 'form-control'}),
			'preco_unidade': forms.TextInput(attrs={'class': 'form-control '}),
			'valor_total': forms.NumberInput(attrs={'class': 'form-control', 'onfocus':'soma()'}),
			
		}

	def save(self, commit=True):
		instance = super(VendaForm, self).save(commit=False)
		
		instance.user = self.request_user
		instance.data_cadastro = timezone.now()
		instance.propriedade = self.request_user.perfilusuario.propriedade
		instance.status_lote = "1"

		if commit:
			instance.save()
			self.save_m2m()
		return instance


class CompraForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.request_user = kwargs.pop('request_user')
		super(CompraForm, self).__init__(*args, **kwargs)

		self.fields["lote"].initial = ''

	class Meta:
		model = Compra
		fields = '__all__'
		exclude = ['user','propriedade','status_lote']
		widgets = {
			'data_compra': forms.DateInput(attrs={'class': 'date-picker form-control'}),
			'lote': forms.NumberInput(attrs={'class': 'form-control'}),
			'fornecedor': forms.Select(attrs={'class': 'form-control'}),
			'produto': forms.Select(attrs={'class': 'form-control'}),
			'tipo_unidade': forms.Select(attrs={'class': 'form-control'}),
			'quantidade': forms.NumberInput(attrs={'class': 'form-control'}),
			'preco_unidade': forms.TextInput(attrs={'class': 'form-control '}),
			'valor_total': forms.NumberInput(attrs={'class': 'form-control', 'onfocus':'soma()'}),
			'lote': forms.NumberInput(attrs={'class': 'form-control'}),
			
		}

	def save(self, commit=True):
		instance = super(CompraForm, self).save(commit=False)
		
		instance.user = self.request_user
		instance.data_cadastro = timezone.now()
		instance.propriedade = self.request_user.perfilusuario.propriedade
		instance.status_lote = "1"

		if commit:
			instance.save()
			self.save_m2m()
		return instance

comercializacao/views.py
# coding: utf-8

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ImproperlyConfigured
from django.core.urlresolvers import reverse_lazy, reverse
from django.forms import models as model_forms, ModelChoiceField
from django.forms.formsets import formset_factory
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import redirect, render, get_object_or_404, render_to_response
from django.contrib.admin.views.decorators import staff_member_required
from django.apps import apps

from django.contrib.auth.models import User

from django.utils import timezone
import datetime

from django.conf import settings

from cadastro.models import (
	PerfilUsuario,
	Propriedade,
	ClienteFornecedor,
	)

from comercializacao.models import (
	Venda,
	Compra,
    )

from .forms import (
	VendaForm,
	CompraForm,
	)


@login_required
def venda_cadastrar(request):

	form = VendaForm(
		data=request.POST or None,
		request_user=request.user,
	)

	if request.POST:
		
		if form.is_valid():

			f = form.save()

			messages.success(request, u'Venda cadastrada com sucesso')
			return HttpResponseRedirect(reverse_lazy('venda_listar'))

	context = {
		'form': form,
	}

	return render(request, 'comercializacao/venda_cadastrar.html', context)

@login_required
def ajax_lote_venda(request, origem, lote):
    '''Carrega ultimo lote de venda com base no lote do colheita '''

    if origem == "1":
    	lote = Venda.objects.filter(lote_colheita_id=int(lote)).order_by('-lote').first()
    else:
    	lote = Venda.objects.filter(lote_compra_id=int(lote)).order_by('-lote').first()

    if lote is None:
    	lote = 1
    else:
    	lote = lote.lote + 1

    return HttpResponse(lote)


@login_required
def venda_listar(request):

	lote = Venda.objects.get_queryset_by_user(request.user).order_by('-data_venda')

	context = {
		'lote': lote,
	}

	return render(request, 'comercializacao/venda_listar.html', context)


@login_required
def venda_editar(request, lote):

	lote = Venda.objects.get(pk=int(lote))

	form = VendaForm(request.POST or None, instance=lote, request_user=request.user)

	if request.method == 'POST':
		
		if form.is_valid():

			f = form.save()

			messages.success(request, u'Venda editado com sucesso')
			return HttpResponseRedirect(reverse_lazy('venda_listar'))

	context = {
		'form': form,
	}

	return render(request, 'comercializacao/venda_editar.html', context)


@login_required
def venda_remover(request, lote):

	lote = Venda.objects.get(pk=int(lote))

	lote.delete()

	messages.success(request, u'Venda removida com sucesso')
	return HttpResponseRedirect(reverse_lazy('venda_listar'))	


@login_required
def venda_fechar_abrir(request, lote):

	lote = Venda.objects.get(pk=int(lote))
	
	if lote.status_lote == '1':
		lote.status_lote = '2'
		lote.save()

	elif lote.status_lote == '2':
		lote.status_lote = '1'
		lote.save()

	messages.success(request, u'Lote fechado/aberto com sucesso')
	return HttpResponseRedirect(reverse_lazy('venda_listar'))




@login_required
def compra_cadastrar(request):

	form = CompraForm(
		data=request.POST or None,
		request_user=request.user,
	)

	lote = Compra.objects.get_queryset_by_user(request.user).order_by('-lote').first()

	if lote is None:
		lote = 1
	else:
		lote = lote.lote + 1


	if request.POST:
		
		if form.is_valid():

			f = form.save()

			messages.success(request, u'Compra cadastrada com sucesso')
			return HttpResponseRedirect(reverse_lazy('compra_listar'))

	context = {
		'form': form,
		'lote': lote,
	}

	return render(request, 'comercializacao/compra_cadastrar.html', context)



@login_required
def compra_listar(request):

	lote = Compra.objects.get_queryset_by_user(request.user).order_by('-data_compra')

	context = {
		'lote': lote,
	}

	return render(request, 'comercializacao/compra_listar.html', context)


@login_required
def compra_editar(request, lote):

	lote = Compra.objects.get(pk=int(lote))

	form = CompraForm(request.POST or None, instance=lote, request_user=request.user)

	if request.method == 'POST':
		
		if form.is_valid():

			f = form.save()

			messages.success(request, u'Compra editado com sucesso')
			return HttpResponseRedirect(reverse_lazy('compra_listar'))

	context = {
		'form': form,
	}

	return render(request, 'comercializacao/compra_editar.html', context)


@login_required
def compra_remover(request, lote):

	lote = Compra.objects.get(pk=int(lote))

	lote.delete()

	messages.success(request, u'Compra removida com sucesso')
	return HttpResponseRedirect(reverse_lazy('compra_listar'))	


@login_required
def compra_fechar_abrir(request, lote):

	lote = Compra.objects.get(pk=int(lote))
	
	if lote.status_lote == '1':
		lote.status_lote = '2'
		lote.save()

	elif lote.status_lote == '2':
		lote.status_lote = '1'
		lote.save()

	messages.success(request, u'Lote fechado/aberto com sucesso')
	return HttpResponseRedirect(reverse_lazy('compra_listar'))

templates/comercializacao/compra_cadastrar.html
{% extends 'base.html' %}

{% load static  %}

{% block menu_comercializacao %}active{% endblock menu_comercializacao %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
{% endblock extra_css %}


{% block content %}

<div class="container">

	<h3>Compra</h3>

	<p>&nbsp;</p>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="{% url 'compra_listar' %}">Listar</a></li>
		<li role="presentation" class="active"><a href="#">Cadastrar</a></li>
		
	</ul>

	<p>&nbsp;</p>
	<form name="compra" method="POST" class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
		<div class="form-group">
			<label for="propriedade" class="col-sm-2 control-label">Propriedade</label>
			<div class="col-sm-3">
				<input class="form-control" id="propriedade" maxlength="250" name="propriedade" type="text" value="{{ request.user.perfilusuario.propriedade }}" disabled/>
			</div>
		</div>
		<div class="form-group">
			<label for="data_compra" class="col-sm-2 control-label">Data da compra</label>
			<div class="col-sm-2">
				<div class="input-group">
					{{ form.data_compra }}
					<label for="id_data_compra" class="input-group-addon btn">
						<span class="glyphicon glyphicon-calendar"></span>
					</label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="lote" class="col-sm-2 control-label">Lote Compra</label>
			<div class="col-sm-2">
				<input class="form-control" id="lote" name="lote" type="number" value="{{ lote }}" >
			</div>
		</div>		
		<div class="form-group">
			<label for="fornecedor" class="col-sm-2 control-label">Fornecedor</label>
			<div class="col-sm-5">
				{{ form.fornecedor }}
			</div>
		</div>
		<div class="form-group">
			<label for="produto" class="col-sm-2 control-label">Produto</label>
			<div class="col-sm-3">
				{{ form.produto }}
			</div>
		</div>
		<div class="form-group">
			<label for="quantidade" class="col-sm-2 control-label">Unidades compradas</label>
			<div class="col-sm-2">
				{{ form.quantidade }}
			</div>
		</div>
		<div class="form-group">
			<label for="tipo_unidade" class="col-sm-2 control-label">Tipo unidade</label>
			<div class="col-sm-2">
				{{ form.tipo_unidade }}
			</div>
		</div>
		<div class="form-group">
			<label for="preco_unidade" class="col-sm-2 control-label">Preço unidade</label>
			<div class="col-sm-2">
				{{ form.preco_unidade }}
			</div>
		</div>
		<div class="form-group">
			<label for="valor_total" class="col-sm-2 control-label">Preço total</label>
			<div class="col-sm-2">
				{{ form.valor_total }}
			</div>
		</div>

		<button type="submit" class="btn btn-primary">Cadastrar compra</button>
	</form>
	<p>&nbsp;</p>

</div>

{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/compra_cadastrar.js' %}"></script>

<script src="{% static 'js/formset.js' %}"></script>

<script type="text/javascript">
$(function() {

	initFormSets({prefixes:['compra']});

	$(".date-picker").datepicker();
	
});
</script>

<script>
	function soma()
	{
		compra.id_valor_total.value = (compra.id_quantidade.value*1) * (compra.id_preco_unidade.value*1)
	}
</script>

{% endblock extra_js %}

templates/comercializacao/compra_editar.html
{% extends 'base.html' %}

{% load static  %}

{% block menu_comercializacao %}active{% endblock menu_comercializacao %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
{% endblock extra_css %}


{% block content %}

<div class="container">

	<h3>Compra</h3>

	<p>&nbsp;</p>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="{% url 'compra_listar' %}">Listar</a></li>
		<li role="presentation" class="active"><a href="#">Cadastrar</a></li>
		
	</ul>

	<p>&nbsp;</p>
	<form name="compra" method="POST" class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
		<div class="form-group">
			<label for="propriedade" class="col-sm-2 control-label">Propriedade</label>
			<div class="col-sm-3">
				<input class="form-control" id="propriedade" maxlength="250" name="propriedade" type="text" value="{{ request.user.perfilusuario.propriedade }}" disabled/>
			</div>
		</div>
		<div class="form-group">
			<label for="data_compra" class="col-sm-2 control-label">Data da compra</label>
			<div class="col-sm-2">
				<div class="input-group">
					{{ form.data_compra }}
					<label for="id_data_compra" class="input-group-addon btn">
						<span class="glyphicon glyphicon-calendar"></span>
					</label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="cliente" class="col-sm-2 control-label">Cliente</label>
			<div class="col-sm-5">
				{{ form.cliente }}
			</div>
		</div>
		<div class="form-group">
			<label for="origem" class="col-sm-2 control-label">Origem</label>
			<div class="col-sm-2">
				{{ form.origem }}
			</div>
		</div>
		<div id="lote_colheita">
			<div class="form-group">
				<label for="lote_colheita" class="col-sm-2 control-label">Lote Colheita</label>
				<div class="col-sm-5">
					{{ form.lote_colheita }}
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="lote" class="col-sm-2 control-label">Lote Compra</label>
			<div class="col-sm-2">
				{{ form.lote }}
			</div>
		</div>
		<div class="form-group">
			<label for="quantidade" class="col-sm-2 control-label">Unidades vendidas</label>
			<div class="col-sm-2">
				{{ form.quantidade }}
			</div>
		</div>
		<div class="form-group">
			<label for="preco_unidade" class="col-sm-2 control-label">Preço unidade</label>
			<div class="col-sm-2">
				{{ form.preco_unidade }}
			</div>
		</div>
		<div class="form-group">
			<label for="valor_total" class="col-sm-2 control-label">Preço total</label>
			<div class="col-sm-2">
				{{ form.valor_total }}
			</div>
		</div>

		<button type="submit" class="btn btn-primary">Editar compra</button>
	</form>
	<p>&nbsp;</p>

</div>

{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/compra_cadastrar.js' %}"></script>

<script src="{% static 'js/formset.js' %}"></script>

<script type="text/javascript">
$(function() {

	initFormSets({prefixes:['compra']});

	$(".date-picker").datepicker();
	
});
</script>

<script>
	function soma()
	{
		compra.id_valor_total.value = (compra.id_quantidade.value*1) * (compra.id_preco_unidade.value*1)
	}
</script>

{% endblock extra_js %}

templates/comercializacao/compra_listar.html
{% extends 'base.html' %}

{% load static  %}

{% block menu_colheita %}active{% endblock menu_colheita %}

{% block content %}


<div class="container">
	{% include 'messages.html' %}
	<h3>Compra</h3>

	<p>&nbsp;</p>

	<ul class="nav nav-tabs">
		<li role="presentation" class="active"><a href="#">Listar</a></li>
		<li role="presentation"><a href="{% url 'compra_cadastrar' %}">Cadastrar</a></li>
		
	</ul>

	<p>&nbsp;</p>
	<table class=table> 
		<!-- <caption>Optional table caption.</caption> -->
		<thead> 
			<tr>
				<th>Lote</th>
				<th>Data</th> 
				<th>Produto</th>
				<th>Unidades Compradas</th> 
				<th>Valor Total</th>
				<th>Gerenciar</th> 
			</tr> 
		</thead> 
		<tbody> 
			{% for lote in lote %}
			<tr> 
				<th scope=row>{{ lote.lote }}</th> 
				<td>{{ lote.data_compra }}</td> 
				<td>{{ lote.produto }}</td> 
				<td>{{ lote.quantidade }} {{ lote.lote_colheita.get_tipo_unidade_display }}</td> 
				<td>R$ {{ lote.valor_total }}</td> 
				<td>
					{% if lote.status_lote == "1" %}
					<a href="{% url 'compra_fechar_abrir' lote.id %}" onclick="return confirm('Fechar/arquivar lote?')"><img src="{% static 'img/archive.png' %}" alt="fechar lote"></a>
					{% else %}
					<a href="{% url 'compra_fechar_abrir' lote.id %}" onclick="return confirm('Reabrir lote?')"><img src="{% static 'img/open.png' %}" alt="reabrir lote"></a>
					{% endif %}	
					<a href="{% url 'compra_editar' lote.id %}"><img src="{% static 'img/edit.png' %}" alt="editar"></a>
					<a href="{% url 'compra_remover' lote.id %}" onclick="return confirm('Remover lote?')"><img src="{% static 'img/delete.png' %}" alt="apagar"></a>
				</td>
			</tr> 
			{% endfor %}

		</tbody> 
	</table> 


</div>

{% endblock content %}

templates/comercializacao/venda_listar.html
{% extends 'base.html' %}

{% load static  %}

{% block menu_colheita %}active{% endblock menu_colheita %}

{% block content %}


<div class="container">
	{% include 'messages.html' %}
	<h3>Venda</h3>

	<p>&nbsp;</p>

	<ul class="nav nav-tabs">
		<li role="presentation" class="active"><a href="#">Listar</a></li>
		<li role="presentation"><a href="{% url 'venda_cadastrar' %}">Cadastrar</a></li>
		
	</ul>

	<p>&nbsp;</p>
	<table class=table> 
		<!-- <caption>Optional table caption.</caption> -->
		<thead> 
			<tr>
				<th>Lote</th>
				<th>Data</th> 
				<th>Origem</th> 
				<th>Produto</th>
				<th>Unidades Vendidas</th> 
				<th>Valor Total</th>
				<th>Gerenciar</th> 
			</tr> 
		</thead> 
		<tbody> 
			{% for lote in lote %}
			<tr> 
				{% if lote.origem == "1" %}
					<th scope=row>{{ lote.lote_colheita.lote_plantio.lote }}.{{ lote.lote_colheita.lote }}.{{ lote.lote }}</th> 
					<td>{{ lote.data_venda }}</td> 
					<td>{{ lote.get_origem_display }}</td> 
					<td>{{ lote.lote_colheita.lote_plantio.produto }}</td> 
					<td>{{ lote.quantidade }} {{ lote.lote_colheita.get_tipo_unidade_display }}</td> 
				{% else %}
					<th scope=row>{{ lote.lote_compra.lote }}.{{ lote.lote }}</th> 
					<td>{{ lote.data_venda }}</td> 
					<td>{{ lote.get_origem_display }}</td> 
					<td>{{ lote.lote_compra.produto }}</td> 
					<td>{{ lote.quantidade }} {{ lote.lote_compra.get_tipo_unidade_display }}</td> 

				{% endif %}

				<td>R$ {{ lote.valor_total }}</td> 

				<td>
					{% if lote.status_lote == "1" %}
					<a href="{% url 'venda_fechar_abrir' lote.id %}" onclick="return confirm('Fechar/arquivar lote?')"><img src="{% static 'img/archive.png' %}" alt="fechar lote"></a>
					{% else %}
					<a href="{% url 'venda_fechar_abrir' lote.id %}" onclick="return confirm('Reabrir lote?')"><img src="{% static 'img/open.png' %}" alt="reabrir lote"></a>
					{% endif %}	
					<a href="{% url 'venda_editar' lote.id %}"><img src="{% static 'img/edit.png' %}" alt="editar"></a>
					<a href="{% url 'venda_remover' lote.id %}" onclick="return confirm('Remover lote?')"><img src="{% static 'img/delete.png' %}" alt="apagar"></a>
				</td>
			</tr> 
			{% endfor %}

		</tbody> 
	</table> 


</div>

{% endblock content %}