cadastro/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy
from django.contrib import admin

from . import views

urlpatterns = [

	url(r'^produto_cadastrar/$', views.produto_cadastrar, name='produto_cadastrar'),
	url(r'^produto_listar/$', views.produto_listar, name='produto_listar'),
	url(r'^produto_editar/(?P<id>[-\w]+)/$', views.produto_editar, name='produto_editar'),
	url(r'^produto_remover/(?P<id>[-\w]+)/$', views.produto_remover, name='produto_remover'),

	url(r'^equipamento_cadastrar/$', views.equipamento_cadastrar, name='equipamento_cadastrar'),
	url(r'^equipamento_listar/$', views.equipamento_listar, name='equipamento_listar'),
	url(r'^equipamento_editar/(?P<id>[-\w]+)/$', views.equipamento_editar, name='equipamento_editar'),
	url(r'^equipamento_remover/(?P<id>[-\w]+)/$', views.equipamento_remover, name='equipamento_remover'),

	url(r'^insumo_cadastrar/$', views.insumo_cadastrar, name='insumo_cadastrar'),
	url(r'^insumo_listar/$', views.insumo_listar, name='insumo_listar'),
	url(r'^insumo_editar/(?P<id>[-\w]+)/$', views.insumo_editar, name='insumo_editar'),
	url(r'^insumo_remover/(?P<id>[-\w]+)/$', views.insumo_remover, name='insumo_remover'),

	url(r'^mdo_cadastrar/$', views.mdo_cadastrar, name='mdo_cadastrar'),
	url(r'^mdo_listar/$', views.mdo_listar, name='mdo_listar'),
	url(r'^mdo_editar/(?P<id>[-\w]+)/$', views.mdo_editar, name='mdo_editar'),
	url(r'^mdo_remover/(?P<id>[-\w]+)/$', views.mdo_remover, name='mdo_remover'),

	url(r'^clientefornecedor_cadastrar/$', views.clientefornecedor_cadastrar, name='clientefornecedor_cadastrar'),
	url(r'^clientefornecedor_listar/$', views.clientefornecedor_listar, name='clientefornecedor_listar'),
]

mapa/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

from . import views

urlpatterns = [

    # url(r'^$', TemplateView.as_view(template_name='mapa.html'), name='mapa'),

    url(r'^$', views.index, name='mapa'),


    url(r'^talhoesglebas.geojson$', views.talhoesglebas, name='talhoesglebas'),
    url(r'^propriedades.geojson$', views.propriedades, name='propriedades'),

]

cadastro/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.gis.db import models
from django.contrib.auth.models import User
from django import utils
from django.utils import timezone

TIPO_CHOICES = (
    ('1', 'Cliente'),
    ('2', 'Fornecedor'),
)

UNIDADE_CHOICES = (
    ('1', 'Kg'),
    ('2', 'Lt'),
)

TIPO_PESSOA_CHOICES = (
    ('1', 'Pessoa Física'),
    ('2', 'Pessoa Jurídica'),
)

TIPO_INSUMO_CHOICES = (
    ('1', 'Adubo'),
    ('2', 'Agrotóxico'),
)

TIPO_PLANTIO_CHOICES = (
    ('1', 'Muda'),
    ('2', 'Semente'),
)


class PerfilUsuario(models.Model):
    '''Perfil adicional dos usuarios'''

    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)
    propriedade = models.ForeignKey('Propriedade', null=True, blank=True, on_delete=models.CASCADE)

    def __unicode__(self):
        return str(self.user)

    class Meta:
        ordering = ['user']


class TipoCentroCusto(models.Model):
	tipo = models.CharField(max_length=100, blank=True, null=True)

	def __unicode__(self):
		return self.tipo

	class Meta:
		verbose_name = 'Tipo de Centro de Custo'
		verbose_name_plural = 'Tipos de Centros de Custo'
		ordering = ['tipo']


class TipoClasse(models.Model):
	tipo = models.CharField(max_length=100, blank=True, null=True)

	def __unicode__(self):
		return self.tipo

	class Meta:
		verbose_name = 'Tipo de Classe'
		verbose_name_plural = 'Tipos de Classes'
		ordering = ['tipo']


class TipoContratacao(models.Model):
	tipo = models.CharField(max_length=100, blank=True, null=True)

	def __unicode__(self):
		return self.tipo

	class Meta:
		verbose_name = 'Tipo de Contratacao'
		verbose_name_plural = 'Tipos de Contratacao'
		ordering = ['tipo']


class TipoEquipamento(models.Model):
	tipo = models.CharField(max_length=100, blank=True, null=True)

	def __unicode__(self):
		return self.tipo

	class Meta:
		verbose_name = 'Tipo de Equipamento'
		verbose_name_plural = 'Tipos de Equipamentos'
		ordering = ['tipo']


class TipoInsumo(models.Model):
	nome = models.CharField(max_length=100)
	tipo = models.CharField('Tipo', max_length=1, choices=TIPO_INSUMO_CHOICES)
	unidade = models.CharField('Unidade', max_length=1, choices=UNIDADE_CHOICES)
	classe = models.ForeignKey(TipoClasse, blank=True, null=True, on_delete=models.CASCADE)
	dosagem_indicada = models.CharField(max_length=100, null=True, blank=True)
	carencia_indicada = models.SmallIntegerField(null=True, blank=True)

	def __unicode__(self):
		return self.nome

	class Meta:
		verbose_name = 'Tipo de Insumo'
		verbose_name_plural = 'Tipos de Insumos'
		ordering = ['nome']


class FilterUserManager(models.Manager):
	def get_queryset_by_user(self, user):
		qs = super(FilterUserManager, self).get_queryset()
		if user.perfilusuario.propriedade is None:
			return qs
		return qs.filter(propriedade=user.perfilusuario.propriedade)


class Propriedade(models.Model):
	nome = models.CharField(max_length=250)
	area = models.FloatField(blank=True, null=True)
	talhoes = models.SmallIntegerField(null=True, blank=True)
	glebas = models.SmallIntegerField(null=True, blank=True)
	geom = models.MultiPolygonField(srid=4326, blank=True, null=True)
	objects = FilterUserManager()

	def __unicode__(self): 
		return self.nome

	@property
	def propriedade(self):
		return unicode(self.id)

	@property
	def nome_propriedade(self):
		return unicode(self.nome)

	class Meta:
		verbose_name = 'Propriedade'
		verbose_name_plural = 'Propriedades'
		ordering = ['nome']


class Responsavel(models.Model):
	'''Pessoas'''

	propriedade = models.ForeignKey(Propriedade, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	nome = models.CharField(max_length=255, null=True, blank=True)
	cargo_funcao = models.CharField(max_length=255, null=True, blank=True)
	telefone = models.CharField(max_length=10, null=True, blank=True)

	def __unicode__(self):
		return unicode(self.nome)

	class Meta:
		verbose_name = 'Responsavel'
		verbose_name_plural = 'Responsaveis'



class ClienteFornecedor(models.Model):
	propriedade = models.ForeignKey(Propriedade, on_delete=models.CASCADE)
	tipo = models.CharField('Tipo Cadastro', max_length=1, choices=TIPO_CHOICES)
	tipo_pessoa = models.CharField('Tipo Pessoa', max_length=1, choices=TIPO_PESSOA_CHOICES)
	razao_social = models.CharField(max_length=250, null=True, blank=True)
	nome_fantasia = models.CharField(max_length=250, null=True, blank=True)
	cpf_cnpj = models.CharField(max_length=14, null=True, blank=True)
	nome_contato = models.CharField(max_length=250, null=True, blank=True)
	email = models.CharField(max_length=250, null=True, blank=True)
	telefone = models.CharField(max_length=10, null=True, blank=True)
	cep = models.CharField('CEP', max_length=9, null=True, blank=True)
	logradouro = models.CharField('Logradouro', max_length=200, null=True, blank=True)
	numero = models.CharField('Número', max_length=100, null=True, blank=True)
	complemento = models.CharField('Complemento', max_length=200, null=True, blank=True)
	bairro = models.CharField('Bairro', max_length=100, null=True, blank=True)
	geom = models.PointField('Latitude/Longitude', null=True, blank=True)
	
	objects = FilterUserManager()

	def __unicode__(self): 
		return self.nome_fantasia

	class Meta:
		verbose_name = 'Cliente/Fornecedor'
		verbose_name_plural = 'Clientes/Fornecedores'
		ordering = ['nome_fantasia']


class MaoDeObra(models.Model):
	propriedade = models.ForeignKey(Propriedade, on_delete=models.CASCADE)
	nome = models.CharField(max_length=100)
	matricula = models.CharField(max_length=100)
	funcao = models.CharField(max_length=100, null=True, blank=True)
	regime_contratacao = models.ForeignKey(TipoContratacao, null=True, blank=True, on_delete=models.CASCADE)
	data_admissao = models.DateField(null=True, blank=True)
	carga_horaria = models.SmallIntegerField(blank=True, null=True)
	centro_custo = models.ForeignKey(TipoCentroCusto, null=True, blank=True, on_delete=models.CASCADE)
	salario = models.FloatField(blank=True, null=True)
	encargos_trabalhistas = models.FloatField(blank=True, null=True)
	beneficios = models.FloatField(blank=True, null=True)
	custo_hora = models.FloatField(blank=True, null=True)

	objects = FilterUserManager()

	def __unicode__(self): 
		return self.nome

	class Meta:
		verbose_name = 'MaoDeObra'
		verbose_name_plural = 'MaoDeObra'
		ordering = ['nome','funcao']


class Produto(models.Model):
	propriedade = models.ForeignKey(Propriedade, on_delete=models.CASCADE)
	produto = models.CharField(max_length=100)
	tipo = models.CharField(max_length=100, null=True, blank=True)
	variedade = models.CharField(max_length=100, null=True, blank=True)
	ciclo_viveiro = models.SmallIntegerField(blank=True, null=True)
	ciclo_campo = models.SmallIntegerField(blank=True, null=True)
	celulas_bandeja = models.SmallIntegerField(blank=True, null=True)
	densidade = models.FloatField(blank=True, null=True)
	tipo_plantio = models.CharField('Tipo Plantio', max_length=1, choices=TIPO_PLANTIO_CHOICES, null=True, blank=True)

	objects = FilterUserManager()

	def __unicode__(self): 
		if not self.tipo:
			return unicode(self.produto)
		return unicode(self.produto) + ' ' + unicode(self.tipo)

	class Meta:
		verbose_name = 'Produto'
		verbose_name_plural = 'Produtos'
		ordering = ['produto']


class Equipamento(models.Model):
	propriedade = models.ForeignKey(Propriedade, on_delete=models.CASCADE)
	equipamento = models.ForeignKey(TipoEquipamento, on_delete=models.CASCADE)
	fabricante = models.CharField(max_length=100, null=True, blank=True)
	valor_inicial = models.FloatField(blank=True, null=True)
	depreciacao = models.FloatField(blank=True, null=True)
	manutencao = models.FloatField(blank=True, null=True)
	custo_hora = models.FloatField(blank=True, null=True)
	ano = models.CharField(max_length=4, null=True, blank=True)

	objects = FilterUserManager()

	def __unicode__(self): 
		return unicode(self.equipamento)

	class Meta:
		verbose_name = 'Equipamento'
		verbose_name_plural = 'Equipamentos'
		ordering = ['equipamento']


class Insumo(models.Model):
	propriedade = models.ForeignKey(Propriedade, on_delete=models.CASCADE)
	insumo = models.ForeignKey(TipoInsumo, on_delete=models.CASCADE)
	fabricante = models.CharField(max_length=100, null=True, blank=True)
	data_compra = models.DateField(blank=True, null=True)
	data_validade = models.DateField(blank=True, null=True)
	preco_unidade = models.FloatField(blank=True, null=True)
	quantidade = models.FloatField(blank=True, null=True)
	valor_total = models.FloatField(blank=True, null=True)

	objects = FilterUserManager()

	def __unicode__(self): 
		return unicode(self.insumo)

	class Meta:
		verbose_name = 'insumo'
		verbose_name_plural = 'Insumos'
		ordering = ['insumo']

cadastro/forms.py
# -*- coding: utf-8  -*-

from django.forms import inlineformset_factory
from django import forms
from django.contrib.auth.models import User
from django.utils import timezone

from cadastro.models import (
	Equipamento,
	Propriedade,
	Insumo,
	Produto,
	MaoDeObra,
	ClienteFornecedor,
	)


class ProdutoForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.request_user = kwargs.pop('request_user')
		super(ProdutoForm, self).__init__(*args, **kwargs)

	class Meta:
		model = Produto
		fields = '__all__'
		exclude = ['user','propriedade']
		widgets = {
			'produto': forms.TextInput(attrs={'class': 'form-control'}),
			'tipo': forms.TextInput(attrs={'class': 'form-control'}),
			'variedade': forms.TextInput(attrs={'class': 'form-control'}),
			'ciclo_viveiro': forms.NumberInput(attrs={'class': 'form-control'}),
			'ciclo_campo': forms.NumberInput(attrs={'class': 'form-control'}),
			'celulas_bandeja': forms.NumberInput(attrs={'class': 'form-control'}),
			'densidade': forms.NumberInput(attrs={'class': 'form-control'}),
			'tipo_plantio': forms.Select(attrs={'class': 'form-control'}),
		}

	def save(self, commit=True):
		instance = super(ProdutoForm, self).save(commit=False)
		
		instance.user = self.request_user
		instance.data_cadastro = timezone.now()
		instance.propriedade = self.request_user.perfilusuario.propriedade

		if commit:
			instance.save()
			self.save_m2m()
		return instance


class EquipamentoForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.request_user = kwargs.pop('request_user')
		super(EquipamentoForm, self).__init__(*args, **kwargs)

	class Meta:
		model = Equipamento
		fields = '__all__'
		exclude = ['user','propriedade']
		widgets = {
			'equipamento': forms.Select(attrs={'class': 'form-control'}),
			'fabricante': forms.TextInput(attrs={'class': 'form-control'}),
			'valor_inicial': forms.TextInput(attrs={'class': 'form-control'}),
			'depreciacao': forms.NumberInput(attrs={'class': 'form-control'}),
			'manutencao': forms.NumberInput(attrs={'class': 'form-control'}),
			'custo_hora': forms.NumberInput(attrs={'class': 'form-control'}),
			'ano': forms.NumberInput(attrs={'class': 'form-control'}),
		}

	def save(self, commit=True):
		instance = super(EquipamentoForm, self).save(commit=False)
		
		instance.user = self.request_user
		instance.data_cadastro = timezone.now()
		instance.propriedade = self.request_user.perfilusuario.propriedade

		if commit:
			instance.save()
			self.save_m2m()
		return instance


class InsumoForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.request_user = kwargs.pop('request_user')
		super(InsumoForm, self).__init__(*args, **kwargs)

	class Meta:
		model = Insumo
		fields = '__all__'
		exclude = ['user','propriedade']
		widgets = {
			'insumo': forms.Select(attrs={'class': 'form-control'}),
			'fabricante': forms.TextInput(attrs={'class': 'form-control'}),
			'data_compra': forms.DateInput(attrs={'class': 'date-picker form-control'}),
			'data_validade': forms.DateInput(attrs={'class': 'date-picker form-control'}),
			'preco_unidade': forms.NumberInput(attrs={'class': 'form-control'}),
			'quantidade': forms.NumberInput(attrs={'class': 'form-control'}),
			'valor_total': forms.NumberInput(attrs={'class': 'form-control'}),
		}

	def save(self, commit=True):
		instance = super(InsumoForm, self).save(commit=False)
		
		instance.user = self.request_user
		instance.data_cadastro = timezone.now()
		instance.propriedade = self.request_user.perfilusuario.propriedade

		if commit:
			instance.save()
			self.save_m2m()
		return instance


class MaoDeObraForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.request_user = kwargs.pop('request_user')
		super(MaoDeObraForm, self).__init__(*args, **kwargs)

	class Meta:
		model = MaoDeObra
		fields = '__all__'
		exclude = ['user','propriedade']
		widgets = {
			'nome': forms.TextInput(attrs={'class': 'form-control'}),
			'matricula': forms.TextInput(attrs={'class': 'form-control'}),
			'funcao': forms.TextInput(attrs={'class': 'form-control'}),
			'nome': forms.TextInput(attrs={'class': 'form-control'}),
			'regime_contratacao': forms.Select(attrs={'class': 'form-control'}),
			'data_admissao': forms.DateInput(attrs={'class': 'date-picker form-control'}),
			'carga_horaria': forms.NumberInput(attrs={'class': 'form-control'}),
			'salario': forms.NumberInput(attrs={'class': 'form-control'}),
			'encargos_trabalhistas': forms.NumberInput(attrs={'class': 'form-control'}),
			'beneficios': forms.NumberInput(attrs={'class': 'form-control'}),
			'custo_hora': forms.NumberInput(attrs={'class': 'form-control'}),
		}

	def save(self, commit=True):
		instance = super(MaoDeObraForm, self).save(commit=False)
		
		instance.user = self.request_user
		instance.data_cadastro = timezone.now()
		instance.propriedade = self.request_user.perfilusuario.propriedade

		if commit:
			instance.save()
			self.save_m2m()
		return instance

class ClienteFornecedorForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		self.request_user = kwargs.pop('request_user')
		super(ClienteFornecedorForm, self).__init__(*args, **kwargs)

	class Meta:
		model = ClienteFornecedor
		fields = '__all__'
		exclude = ['user','propriedade']
		widgets = {
			'tipo': forms.Select(attrs={'class': 'form-control'}),
			'tipo_pessoa': forms.Select(attrs={'class': 'form-control'}),
			'razao_social': forms.TextInput(attrs={'class': 'form-control'}),
			'nome_fantasia': forms.TextInput(attrs={'class': 'form-control'}),
		}

	def save(self, commit=True):
		instance = super(ClienteFornecedorForm, self).save(commit=False)
		
		instance.user = self.request_user
		instance.data_cadastro = timezone.now()
		instance.propriedade = self.request_user.perfilusuario.propriedade

		if commit:
			instance.save()
			self.save_m2m()
		return instance

templates/cadastro/clientefornecedor_listar.html
{% extends 'base.html' %}

{% load static  %}

{% block menu_produto %}active{% endblock menu_produto %}

{% block content %}


<div class="container">
	<p>
	{% include 'messages.html' %}
	<h3>Clientes/Fornecedores</h3>

	<p>&nbsp;</p>

	<ul class="nav nav-tabs">
		<li role="presentation" class="active"><a href="#">Listar</a></li>
		<li role="presentation"><a href="{% url 'clientefornecedor_cadastrar' %}">Cadastrar</a></li>
		
	</ul>

	<p>&nbsp;</p>
	<table class=table> 
		<!-- <caption>Optional table caption.</caption> -->
		<thead> 
			<tr>
				<th>#</th>
				<th>Tipo</th> 
				<th>Tipo Pessoa</th> 
				<th>Razão Social</th>
				<th>Gerenciar</th> 
			</tr> 
		</thead> 
		<tbody> 
			{% for p in clientefornecedor %}
			<tr> 
				<th scope=row>{{ p.id }}</th> 
				<td>{{ p.get_tipo_display }}</td> 
				<td>{{ p.get_tipo_pessoa_display }}</td>
				<td>{{ p.razao_social }}</td> 

				<td>
					<a href="{% url 'produto_editar' p.id %}"><img src="{% static 'img/edit.png' %}" alt="editar"></a>
					<a href="{% url 'produto_remover' p.id %}" onclick="return confirm('Apagar registro?')"><img src="{% static 'img/delete.png' %}" alt="apagar"></a>
				</td> 
			</tr> 
			{% endfor %}

		</tbody> 
	</table> 


	</div>

	{% endblock content %}

templates/cadastro/insumo_cadastrar.html
{% extends 'base.html' %}

{% load static  %}

{% block menu_produtos %}active{% endblock menu_produtos %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
{% endblock extra_css %}


{% block content %}


<div class="container">

	<h3>Insumos</h3>

	<p>&nbsp;</p>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="{% url 'insumo_listar' %}">Listar</a></li>
		<li role="presentation" class="active"><a href="#">Cadastrar</a></li>
		
	</ul>

	<p>&nbsp;</p>
	<form method="POST" class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
		<div class="form-group">
			<label for="propriedade" class="col-sm-2 control-label">Propriedade</label>
			<div class="col-sm-3">
				<input class="form-control" id="propriedade" maxlength="250" name="propriedade"  type="text" value="{{ request.user.perfilusuario.propriedade }}" disabled/>
			</div>
		</div>
		<div class="form-group">
			<label for="produto" class="col-sm-2 control-label">Insumo</label>
			<div class="col-sm-3">
				{{ form.insumo }}
			</div>
		</div>
		<div class="form-group">
			<label for="tipi" class="col-sm-2 control-label">Fabricante</label>
			<div class="col-sm-5">
				{{ form.fabricante }}
			</div>
		</div>
		<div class="form-group">
			<label for="data_compra" class="col-sm-2 control-label">Data da Compra</label>
			<div class="col-sm-2">
				<div class="input-group">
					{{ form.data_compra }}
					<label for="id_data_compra" class="input-group-addon btn">
						<span class="glyphicon glyphicon-calendar"></span>
					</label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="data_validade" class="col-sm-2 control-label">Data de Validade</label>
			<div class="col-sm-2">
				<div class="input-group">
					{{ form.data_validade }}
					<label for="id_data_compra" class="input-group-addon btn">
						<span class="glyphicon glyphicon-calendar"></span>
					</label>
				</div>
			</div>
		</div>

		<div class="form-group">
			<label for="preco_unidade" class="col-sm-2 control-label">Preço Unidade</label>
			<div class="col-sm-2">
				{{ form.preco_unidade }}
			</div>
		</div>
		<div class="form-group">
			<label for="celulas_bandeja" class="col-sm-2 control-label">Quantidade</label>
			<div class="col-sm-2">
				{{ form.quantidade }}
			</div>
		</div>
		<div class="form-group">
			<label for="valor_total" class="col-sm-2 control-label">Valor Total</label>
			<div class="col-sm-2">
				{{ form.valor_total }}
			</div>
		</div>		

		<button type="submit" class="btn btn-primary">Cadastrar Insumo</button>
	</form>
	<p>&nbsp;</p>

</div>

{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

<script src="{% static 'js/formset.js' %}"></script>

<script type="text/javascript">
$(function() {

	initFormSets({prefixes:['insumo']});

	$(".date-picker").datepicker();
	
});
</script>

{% endblock extra_js %}

templates/cadastro/insumo_editar.html
{% extends 'base.html' %}

{% load static  %}

{% block menu_produtos %}active{% endblock menu_produtos %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
{% endblock extra_css %}


{% block content %}


<div class="container">

	<h3>Insumos</h3>

	<p>&nbsp;</p>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="{% url 'insumo_listar' %}">Listar</a></li>
		<li role="presentation" class="active"><a href="#">Cadastrar</a></li>
		
	</ul>

	<p>&nbsp;</p>
	<form method="POST" class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
		<div class="form-group">
			<label for="propriedade" class="col-sm-2 control-label">Propriedade</label>
			<div class="col-sm-3">
				<input class="form-control" id="id_praga_doenca" maxlength="250" name="praga_doenca" type="text" value="{{ request.user.perfilusuario.propriedade }}" disabled/>
			</div>
		</div>
		<div class="form-group">
			<label for="produto" class="col-sm-2 control-label">Insumo</label>
			<div class="col-sm-3">
				{{ form.insumo }}
			</div>
		</div>
		<div class="form-group">
			<label for="tipi" class="col-sm-2 control-label">Fabricante</label>
			<div class="col-sm-5">
				{{ form.fabricante }}
			</div>
		</div>
		<div class="form-group">
			<label for="data_compra" class="col-sm-2 control-label">Data da Compra</label>
			<div class="col-sm-2">
				<div class="input-group">
					{{ form.data_compra }}
					<label for="id_data_compra" class="input-group-addon btn">
						<span class="glyphicon glyphicon-calendar"></span>
					</label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="data_validade" class="col-sm-2 control-label">Data de Validade</label>
			<div class="col-sm-2">
				<div class="input-group">
					{{ form.data_validade }}
					<label for="id_data_compra" class="input-group-addon btn">
						<span class="glyphicon glyphicon-calendar"></span>
					</label>
				</div>
			</div>
		</div>

		<div class="form-group">
			<label for="preco_unidade" class="col-sm-2 control-label">Preço Unidade</label>
			<div class="col-sm-2">
				{{ form.preco_unidade }}
			</div>
		</div>
		<div class="form-group">
			<label for="celulas_bandeja" class="col-sm-2 control-label">Quantidade</label>
			<div class="col-sm-2">
				{{ form.quantidade }}
			</div>
		</div>
		<div class="form-group">
			<label for="valor_total" class="col-sm-2 control-label">Valor Total</label>
			<div class="col-sm-2">
				{{ form.valor_total }}
			</div>
		</div>		

		<button type="submit" class="btn btn-primary">Editar Insumo</button>
	</form>
	<p>&nbsp;</p>

</div>

{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

<script src="{% static 'js/formset.js' %}"></script>

<script type="text/javascript">
$(function() {

	initFormSets({prefixes:['insumo']});

	$(".date-picker").datepicker();
	
});
</script>

{% endblock extra_js %}