ciclo/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy
from django.contrib import admin

from . import views

urlpatterns = [

	url(r'^preparosolo_cadastrar/$', views.preparosolo_cadastrar, name='preparosolo_cadastrar'),
	url(r'^preparosolo_listar/$', views.preparosolo_listar, name='preparosolo_listar'),
	url(r'^preparosolo_editar/(?P<id>[-\w]+)/$', views.preparosolo_editar, name='preparosolo_editar'),
	url(r'^preparosolo_remover/(?P<id>[-\w]+)/$', views.preparosolo_remover, name='preparosolo_remover'),

	url(r'^adubacao_cadastrar/$', views.adubacao_cadastrar, name='adubacao_cadastrar'),
	url(r'^adubacao_listar/$', views.adubacao_listar, name='adubacao_listar'),
	url(r'^adubacao_editar/(?P<id>[-\w]+)/$', views.adubacao_editar, name='adubacao_editar'),
	url(r'^adubacao_remover/(?P<id>[-\w]+)/$', views.adubacao_remover, name='adubacao_remover'),

	url(r'^fitossanidade_cadastrar/$', views.fitossanidade_cadastrar, name='fitossanidade_cadastrar'),
	url(r'^fitossanidade_listar/$', views.fitossanidade_listar, name='fitossanidade_listar'),
	url(r'^fitossanidade_editar/(?P<id>[-\w]+)/$', views.fitossanidade_editar, name='fitossanidade_editar'),
	url(r'^fitossanidade_remover/(?P<id>[-\w]+)/$', views.fitossanidade_remover, name='fitossanidade_remover'),

	url(r'^semeio_cadastrar/$', views.semeio_cadastrar, name='semeio_cadastrar'),
	url(r'^semeio_listar/$', views.semeio_listar, name='semeio_listar'),
	url(r'^semeio_remover/(?P<id>[-\w]+)/$', views.semeio_remover, name='semeio_remover'),
	url(r'^semeio_editar/(?P<id>[-\w]+)/$', views.semeio_editar, name='semeio_editar'),
	url(r'^semeio_fechar_abrir/(?P<id>[-\w]+)/$',  views.semeio_fechar_abrir, name='semeio_fechar_abrir'),

	url(r'^ajax_celulas/(?P<id_produto>[-\w]+)/$', views.ajax_celulas, name='ajax_celulas'),

	url(r'^plantio_cadastrar/$', views.plantio_cadastrar, name='plantio_cadastrar'),
	url(r'^plantio_listar/$', views.plantio_listar, name='plantio_listar'),
	url(r'^plantio_relatorio/$', views.plantio_relatorio, name='plantio_relatorio'),
	url(r'^plantio_remover/(?P<id>[-\w]+)/$', views.plantio_remover, name='plantio_remover'),
	url(r'^plantio_editar/(?P<id>[-\w]+)/$', views.plantio_editar, name='plantio_editar'),
	url(r'^plantio_fechar_abrir/(?P<id>[-\w]+)/$',  views.plantio_fechar_abrir, name='plantio_fechar_abrir'),

	url(r'^ajax_produto/(?P<id>[-\w]+)/$', views.ajax_produto, name='ajax_produto'),
	# url(r'^ajax_origem/(?P<origem>[-\w]+)/$', views.ajax_origem, name='ajax_origem'),
	# url(r'^ajax_lote_prop/(?P<id>[-\w]+)/$', views.ajax_lote_prop, name='ajax_lote_prop'),

	url(r'^colheita_cadastrar/$', views.colheita_cadastrar, name='colheita_cadastrar'),
	url(r'^colheita_listar/$', views.colheita_listar, name='colheita_listar'),
	url(r'^colheita_relatorio/$', views.colheita_relatorio, name='colheita_relatorio'),
	url(r'^colheita_remover/(?P<id>[-\w]+)/$', views.colheita_remover, name='colheita_remover'),
	url(r'^colheita_editar/(?P<id>[-\w]+)/$', views.colheita_editar, name='colheita_editar'),
	url(r'^colheita_fechar_abrir/(?P<id>[-\w]+)/$',  views.colheita_fechar_abrir, name='colheita_fechar_abrir'),

	url(r'^ajax_lote_prop_colheita/(?P<id>[-\w]+)/$', views.ajax_lote_prop_colheita, name='ajax_lote_prop_colheita'),

	url(r'^talhaogleba_detalhe/(?P<talhao>[\d]+)/$', views.talhaogleba_detalhe, name='talhaogleba_detalhe'),

]

mapa/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

from . import views

urlpatterns = [

    # url(r'^$', TemplateView.as_view(template_name='mapa.html'), name='mapa'),

    url(r'^$', views.index, name='mapa'),


    url(r'^talhoesglebas.geojson$', views.talhoesglebas, name='talhoesglebas'),
    url(r'^propriedades.geojson$', views.propriedades, name='propriedades'),

]

ciclo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.gis.db import models
from django.contrib.auth.models import User
from django import utils
from django.utils import timezone

from cadastro.models import (
    Equipamento,
    Propriedade,
    Insumo,
    Produto,
    MaoDeObra,
    FilterUserManager,
    )

from mapa.models import (
    TalhoesGlebas,
    )

ORIGEM_CHOICES = (
    ('1', 'Viveiro'),
    ('2', 'Compra'),
    ('3', 'Colheita'),
    ('4', 'Não Identificado'),
)

TIPO_UNIDADE_CHOICES = (
    ('1', 'Maço(s)'),
    ('2', 'Unidade(s)'),
    ('3', 'Caixa(s)'),
    ('4', 'Kg'),
    ('5', 'Bandeja(s)'),
    ('6', 'Dúzia(s)'),
    ('7', 'Cento(s)'),
)

STATUS_LOTE_CHOICES = (
    ('1', 'Aberto'),
    ('2', 'Encerrado'),
)

TIPO_PLANTIO_CHOICES = (
    ('1', 'Muda'),
    ('2', 'Semente'),
)


class TipoPreparo(models.Model):
	tipo = models.CharField(max_length=100, blank=True, null=True)

	def __unicode__(self):
		return self.tipo

	class Meta:
		verbose_name = 'Tipo de Preparo'
		verbose_name_plural = 'Tipos de Preparo'
		ordering = ['tipo']


class TipoAdubacao(models.Model):
	tipo = models.CharField(max_length=100, blank=True, null=True)

	def __unicode__(self):
		return self.tipo

	class Meta:
		verbose_name = 'Tipo de Adubação'
		verbose_name_plural = 'Tipos de Adubação'
		ordering = ['tipo']


class PreparoSolo(models.Model):
	'''Preparo do Solo'''

	id = models.AutoField(primary_key=True)
	lote = models.IntegerField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	data_preparo = models.DateField()
	propriedade = models.ForeignKey(Propriedade, null=True, blank=True, on_delete=models.CASCADE)
	talhao_gleba = models.ManyToManyField(TalhoesGlebas)
	tipo_preparo = models.ForeignKey(TipoPreparo, on_delete=models.CASCADE)
	equipamento = models.ForeignKey(Equipamento, null=True, blank=True, on_delete=models.CASCADE)
	insumo = models.ForeignKey(Insumo, null=True, blank=True, on_delete=models.CASCADE)
	quantidade = models.FloatField(blank=True, null=True)
	horas_maquina = models.FloatField(blank=True, null=True)
	data_cadastro = models.DateTimeField(blank=True, null=True)

	objects = FilterUserManager()

	def __unicode__(self):
		return unicode(self.id)

	class Meta:
		verbose_name = 'Preparo do Solo'
		verbose_name_plural = 'Preparação do Solo'


class EquipamentoPreparo(models.Model):
	'''Equipamento utilizado - Preparo do Solo'''

	preparo = models.ForeignKey('PreparoSolo', blank=True, null=True, on_delete=models.CASCADE)
	equipamento = models.ForeignKey(Equipamento, blank=True, null=True, on_delete=models.CASCADE)
	horas_maquina = models.SmallIntegerField(blank=True, null=True)

	def __unicode__(self):
		return unicode(self.preparo)


class MdoPreparo(models.Model):
	'''Mão de Obra alocada - Preparo do Solo'''

	preparo = models.ForeignKey('PreparoSolo', blank=True, null=True, related_name='preparo', on_delete=models.CASCADE)
	nome = models.ForeignKey(MaoDeObra, blank=True, null=True, on_delete=models.CASCADE)
	horas = models.SmallIntegerField(blank=True, null=True)

	def __unicode__(self):
		return unicode(self.id)


class Adubacao(models.Model):
	'''Adubação'''

	id = models.AutoField(primary_key=True)
	lote = models.IntegerField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	data_adubacao = models.DateField()
	propriedade = models.ForeignKey(Propriedade, null=True, blank=True, on_delete=models.CASCADE)
	talhao_gleba = models.ManyToManyField(TalhoesGlebas)
	tipo_adubacao = models.ForeignKey(TipoAdubacao, on_delete=models.CASCADE)
	equipamento = models.ForeignKey(Equipamento, null=True, blank=True, on_delete=models.CASCADE)
	insumo = models.ForeignKey(Insumo, on_delete=models.CASCADE)
	quantidade = models.FloatField()
	horas_maquina = models.FloatField(blank=True, null=True)
	data_cadastro = models.DateTimeField(blank=True, null=True)

	objects = FilterUserManager()

	def __unicode__(self):
		return unicode(self.id)

	class Meta:
		verbose_name = 'Adubação'
		verbose_name_plural = 'Adubações'


class MdoAdubacao(models.Model):
	'''Mão de Obra alocada - Adubação'''

	adubacao = models.ForeignKey('Adubacao', blank=True, null=True, related_name='adubacao', on_delete=models.CASCADE)
	nome = models.ForeignKey(MaoDeObra, blank=True, null=True, on_delete=models.CASCADE)
	horas = models.SmallIntegerField(blank=True, null=True)

	def __unicode__(self):
		return unicode(self.adubacao)


class Fitossanidade(models.Model):
	'''Fitossanidade'''

	id = models.AutoField(primary_key=True)
	lote = models.IntegerField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	data_fito = models.DateField()
	propriedade = models.ForeignKey(Propriedade, null=True, blank=True, on_delete=models.CASCADE)
	talhao_gleba = models.ManyToManyField(TalhoesGlebas)
	praga_doenca = models.CharField(max_length=250, null=True, blank=True)
	equipamento = models.ForeignKey(Equipamento, null=True, blank=True, on_delete=models.CASCADE)
	insumo = models.ForeignKey(Insumo, on_delete=models.CASCADE)
	quantidade = models.FloatField()
	dosagem = models.FloatField(blank=True, null=True)
	horas_maquina = models.FloatField(blank=True, null=True)
	data_cadastro = models.DateTimeField(blank=True, null=True)

	objects = FilterUserManager()

	def __unicode__(self):
		return unicode(self.id)

	class Meta:
		verbose_name = 'Fitossanidade'
		verbose_name_plural = 'Fitossanidade'


class MdoFitossanidade(models.Model):
	'''Mão de Obra alocada - Fitossanidade'''

	fitossanidade = models.ForeignKey('Fitossanidade', blank=True, null=True, related_name='fitossanidade', on_delete=models.CASCADE)
	nome = models.ForeignKey(MaoDeObra, blank=True, null=True, on_delete=models.CASCADE)
	horas = models.SmallIntegerField(blank=True, null=True)

	objects = FilterUserManager()

	def __unicode__(self):
		return unicode(self.fitossanidade)


class Semeio(models.Model):
	'''Semeio'''

	id = models.AutoField(primary_key=True)
	lote = models.IntegerField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	data_semeio = models.DateField()
	propriedade = models.ForeignKey(Propriedade, null=True, blank=True, on_delete=models.CASCADE)
	viveiro = models.CharField(blank=True, null=True, max_length=255)
	produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
	n_bandejas = models.SmallIntegerField(blank=True, null=True)
	unidades = models.IntegerField()
	restantes = models.IntegerField(blank=True, null=True)
	status_lote = models.CharField('Status do Lote', max_length=1, choices=STATUS_LOTE_CHOICES)
	data_cadastro = models.DateTimeField(blank=True, null=True)

	objects = FilterUserManager()

	@property
	def unidades_plantadas(self):
		return sum(self.plantio_set.values_list('unidades', flat=True))

	# @property
	# def unidades_restantes(self):
	# 	return unidades - unidades_plantadas

	def __unicode__(self):
		return unicode(self.lote) + ' / ' + unicode(self.produto) + ' / ' + unicode(self.data_semeio)

	class Meta:
		verbose_name = 'Semeio'
		verbose_name_plural = 'Semeios'


class MdoSemeio(models.Model):
	'''Mão de Obra alocada - Semeio'''

	semeio = models.ForeignKey('Semeio', blank=True, null=True, related_name='semeio', on_delete=models.CASCADE)
	nome = models.ForeignKey(MaoDeObra, blank=True, null=True, on_delete=models.CASCADE)
	horas = models.SmallIntegerField(blank=True, null=True)

	def __unicode__(self):
		return unicode(self.semeio)


class Plantio(models.Model):
	'''Plantio'''

	id = models.AutoField(primary_key=True)
	lote = models.IntegerField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	data_plantio = models.DateField()
	propriedade = models.ForeignKey(Propriedade, null=True, blank=True, on_delete=models.CASCADE)
	talhao_gleba = models.ManyToManyField(TalhoesGlebas)
	produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
	origem = models.CharField('Origem', max_length=1, choices=ORIGEM_CHOICES)
	lote_semeio = models.ForeignKey(Semeio, null=True, blank=True, on_delete=models.CASCADE)
	tipo_plantio = models.CharField('Tipo de unidade', max_length=1, choices=TIPO_PLANTIO_CHOICES)
	unidades = models.IntegerField()
	restantes = models.IntegerField(blank=True, null=True)
	status_lote = models.CharField('Status do Lote', max_length=1, choices=STATUS_LOTE_CHOICES)
	data_cadastro = models.DateTimeField(blank=True, null=True)

	objects = FilterUserManager()

	@property
	def unidades_colhidas(self):
		return sum(self.colheita_set.values_list('unidades', flat=True))

	def __unicode__(self):
		return unicode(self.lote) + ' / ' + unicode(self.produto) + ' / ' + unicode(self.data_plantio)

	class Meta:
		verbose_name = 'Plantio'
		verbose_name_plural = 'Plantios'


class MdoPlantio(models.Model):
	'''Mão de Obra alocada - Plantio'''

	plantio = models.ForeignKey('Plantio', blank=True, null=True, related_name='plantio', on_delete=models.CASCADE)
	nome = models.ForeignKey(MaoDeObra, blank=True, null=True, on_delete=models.CASCADE)
	horas = models.SmallIntegerField(blank=True, null=True)

	def __unicode__(self):
		return unicode(self.plantio)


class Colheita(models.Model):
	'''Colheita'''

	id = models.AutoField(primary_key=True)
	lote = models.IntegerField()
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	data_colheita = models.DateField()
	propriedade = models.ForeignKey(Propriedade, null=True, blank=True, on_delete=models.CASCADE)
	lote_plantio = models.ForeignKey(Plantio, on_delete=models.CASCADE)
	unidades = models.IntegerField()
	tipo_unidade = models.CharField('Tipo de unidade', max_length=1, choices=TIPO_UNIDADE_CHOICES)
	sobra = models.FloatField(blank=True, null=True)
	status_lote = models.CharField('Status do Lote', max_length=1, choices=STATUS_LOTE_CHOICES)
	data_cadastro = models.DateTimeField(blank=True, null=True)

	objects = FilterUserManager()

	def __unicode__(self):
		return unicode(self.lote_plantio.lote) + '.' + unicode(self.lote) + ' / ' + unicode(self.lote_plantio.produto) + ' / ' + unicode(self.data_colheita)

	class Meta:

templates/ciclo/adubacao_editar.html
{% extends 'base.html' %}

{% load static  %}

{% block menu_adubacao %}active{% endblock menu_adubacao %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
{% endblock extra_css %}


{% block content %}


<div class="container">

	<h3>Adubação</h3>

	<p>&nbsp;</p>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="{% url 'adubacao_listar' %}">Listar</a></li>
		<li role="presentation" class="active"><a href="#">Cadastrar</a></li>
		
	</ul>

	<p>&nbsp;</p>
	<form method="POST" class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
		<div class="form-group">
			<label for="data_adubacao" class="col-sm-2 control-label">Data da adubação</label>
			<div class="col-sm-2">
				<div class="input-group">
					{{ form.data_adubacao }}
					<label for="id_data_adubacao" class="input-group-addon btn">
						<span class="glyphicon glyphicon-calendar"></span>
	                </label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="lote" class="col-sm-2 control-label">Lote</label>
			<div class="col-sm-2">
				{{ form.lote }}
			</div>
		</div>
		<div class="form-group">
			<label for="tipo_preparo" class="col-sm-2 control-label">Propriedade</label>
			<div class="col-sm-3">
				<input class="form-control" id="id_praga_doenca" maxlength="250" name="praga_doenca" type="text" value="{{ request.user.perfilusuario.propriedade }}" disabled/>
			</div>
		</div>
		<div class="form-group">
			<label for="talhao" class="col-sm-2 control-label">Talhão/Gleba</label>
			<div class="col-sm-3">
				{{ form.talhao_gleba }}
			</div>
		</div>
		<div class="form-group">
			<label for="tipo_preparo" class="col-sm-2 control-label">Tipo da adubação</label>
			<div class="col-sm-3">
				{{ form.tipo_adubacao }}
			</div>
		</div>
		<div class="form-group">
			<label for="equipamento" class="col-sm-2 control-label">Equipamento</label>
			<div class="col-sm-3">
				{{ form.equipamento }}
			</div>
		</div>
		<div class="form-group">
			<label for="horas_maquina" class="col-sm-2 control-label">Horas Máquina</label>
			<div class="col-sm-2">
				{{ form.horas_maquina }}
			</div>
		</div>
		<div class="form-group">
			<label for="insumo" class="col-sm-2 control-label">Insumo</label>
			<div class="col-sm-3">
				{{ form.insumo }}
			</div>
		</div>
		<div class="form-group">
			<label for="quantidade" class="col-sm-2 control-label">Quantidade</label>
			<div class="col-sm-2">
				{{ form.quantidade }}
			</div>
		</div>
		{{ mdo_formset.management_form }}
		<div class="row adubacao_row">
			<div class="form-group">
				<label for="nome" class="col-sm-offset-2 col-sm-3">Trabalhador</label>
				<label for="horas" class="col-sm-2 ">Horas trabalhadas</label>
			</div>
			{% for form_mdo in mdo_formset %}
			<div class="wrapper">

				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-3">
						{{ form_mdo.nome }}
						{% if form_mdo.nome.errors %}
						{% for error in form_mdo.nome.errors %}
						{{ error|escape }}
						{% endfor %}
						{% endif %}
					</div>
					<div class="col-sm-2">
						{{ form_mdo.horas }}
						{% if form_mdo.horas.errors %}
						{% for error in form_mdo.horas.errors %}
						{{ error|escape }}
						{% endfor %}
						{% endif %}
					</div>
				</div>

			</div>
			<div style="display: none">
				{{ form_mdo.id }}
				{{ form_mdo.DELETE }}
			</div>
			{% endfor %}
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-4">
				<a class="btn btn-danger btn-xs removeForm" data-formset="adubacao" title="Remover"><i class="glyphicon glyphicon-minus"></i></a>
				<a class="btn btn-success btn-xs addForm" data-formset="adubacao" title="Adicionar"><i class="glyphicon glyphicon-plus"></i></a>
			</div> 
		</div>


		<button type="submit" class="btn btn-primary">Editar Adubação</button>
	</form>
	<p>&nbsp;</p>

</div>

{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

<script src="{% static 'js/formset.js' %}"></script>

<script type="text/javascript">
$(function() {


	initFormSets({prefixes:['adubacao']});

	$(".date-picker").datepicker();
	
});
</script>

{% endblock extra_js %}

templates/ciclo/colheita_relatorio.html
{% extends 'base.html' %}

{% load static  %}

{% block menu_colheita %}active{% endblock menu_colheita %}

{% block content %}


<div class="container">
	{% include 'messages.html' %}
	<h3>Colheita</h3>

	<p>&nbsp;</p>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="{% url 'colheita_listar' %}">Listar</a></li>
		<li role="presentation"><a href="{% url 'colheita_cadastrar' %}">Cadastrar</a></li>
		<li role="presentation" class="active"><a href="#">Síntese</a></li>
	</ul>

	<p>&nbsp;</p>

	<p><b>Total de lotes:</b> {{ lote.count }}</p>

	<p><b>Número de produtos colhidos:</b> {{ unidade_produto.count }}</p>

	<p><b>Total de unidades colhidas:</b> {{ total_unidades.unidades__sum }}</p>

	<p><b>Colheita por produto:</b></p>
		{% for p in unidade_produto %}
			{{ p.lote_plantio__produto__produto }} {{ p.lote_plantio__produto__tipo }} - {{ p.unidades__sum }}  

			{% ifequal p.tipo_unidade "1" %} Maço(s) {% endifequal %}
			{% ifequal p.tipo_unidade "2" %} Unidade(s) {% endifequal %}
			{% ifequal p.tipo_unidade "4" %} Kg {% endifequal %}
			{% ifequal p.tipo_unidade "6" %} Dúzia(s) {% endifequal %}


			<br>

		{% endfor %}
	</p>

</div>

{% endblock content %}

templates/ciclo/fitossanidade_cadastrar.html
{% extends 'base.html' %}

{% load static  %}

{% block menu_fito %}active{% endblock menu_fito %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
{% endblock extra_css %}


{% block content %}


<div class="container">

	<h3>Fitossanidade</h3>

	<p>&nbsp;</p>

	<ul class="nav nav-tabs">
		<li role="presentation"><a href="{% url 'fitossanidade_listar' %}">Listar</a></li>
		<li role="presentation" class="active"><a href="#">Cadastrar</a></li>
		
	</ul>

	<p>&nbsp;</p>
	{% if form.errors %}
		<div class="alert alert-danger" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			  <span aria-hidden="true">&times;</span>
			</button>
			{% for field in form %}
				{% for error in field.errors %}
						<p><strong>{{ error|escape }}</strong></p>
				{% endfor %}
			{% endfor %}
		</div>
	{% endif %}

	<form method="POST" class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
		<div class="form-group">
			<label for="data_fito" class="col-sm-2 control-label">Data da aplicação</label>
			<div class="col-sm-2">
				<div class="input-group">
					{{ form.data_fito }}
					<label for="id_data_fito" class="input-group-addon btn">
						<span class="glyphicon glyphicon-calendar"></span>
	                </label>
				</div>
			</div>
		</div>
		<div class="form-group">
			<label for="lote" class="col-sm-2 control-label">Lote</label>
			<div class="col-sm-2">
				{{ form.lote }}
			</div>
		</div>
		<div class="form-group">
			<label for="tipo_preparo" class="col-sm-2 control-label">Propriedade</label>
			<div class="col-sm-3">
				<input class="form-control" id="id_praga_doenca" maxlength="250" name="praga_doenca" type="text" value="{{ request.user.perfilusuario.propriedade }}" disabled/>
			</div>
		</div>
		<div class="form-group">
			<label for="talhao" class="col-sm-2 control-label">Talhão/Gleba</label>
			<div class="col-sm-3">
				{{ form.talhao_gleba }}
			</div>
		</div>
		<div class="form-group">
			<label for="equipamento" class="col-sm-2 control-label">Equipamento</label>
			<div class="col-sm-3">
				{{ form.equipamento }}
			</div>
		</div>
		<div class="form-group">
			<label for="horas_maquina" class="col-sm-2 control-label">Horas Máquina</label>
			<div class="col-sm-2">
				{{ form.horas_maquina }}
			</div>
		</div>
		<div class="form-group">
			<label for="praga_doenca" class="col-sm-2 control-label">Praga/Doença</label>
			<div class="col-sm-3">
				{{ form.praga_doenca }}
			</div>
		</div>
		<div class="form-group">
			<label for="insumo" class="col-sm-2 control-label">Insumo</label>
			<div class="col-sm-3">
				{{ form.insumo }}
			</div>
		</div>
		<div class="form-group">
			<label for="quantidade" class="col-sm-2 control-label">Quantidade</label>
			<div class="col-sm-2">
				{{ form.quantidade }}
			</div>
		</div>
		<div class="form-group">
			<label for="dosagem" class="col-sm-2 control-label">Dosagem</label>
			<div class="col-sm-2">
				{{ form.dosagem }}
			</div>
		</div>
		{{ mdo_formset.management_form }}
		<div class="row fitossanidade_row">
			<div class="form-group">
				<label for="nome" class="col-sm-offset-2 col-sm-3">Trabalhador</label>
				<label for="horas" class="col-sm-2 ">Horas trabalhadas</label>
			</div>
			{% for form_mdo in mdo_formset %}
			<div class="wrapper">

				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-3">
						{{ form_mdo.nome }}
						{% if form_mdo.nome.errors %}
						{% for error in form_mdo.nome.errors %}
						{{ error|escape }}
						{% endfor %}
						{% endif %}
					</div>
					<div class="col-sm-2">
						{{ form_mdo.horas }}
						{% if form_mdo.horas.errors %}
						{% for error in form_mdo.horas.errors %}
						{{ error|escape }}
						{% endfor %}
						{% endif %}
					</div>
				</div>

			</div>
			<div style="display: none">
				{{ form_mdo.id }}
				{{ form_mdo.DELETE }}
			</div>
			{% endfor %}
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-4">
				<a class="btn btn-danger btn-xs removeForm" data-formset="fitossanidade" title="Remover"><i class="glyphicon glyphicon-minus"></i></a>
				<a class="btn btn-success btn-xs addForm" data-formset="fitossanidade" title="Adicionar"><i class="glyphicon glyphicon-plus"></i></a>
			</div> 
		</div>


		<button type="submit" class="btn btn-primary">Cadastrar Aplicação</button>
	</form>
	<p>&nbsp;</p>

</div>

{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

<script src="{% static 'js/formset.js' %}"></script>

<script type="text/javascript">
$(function() {


	initFormSets({prefixes:['fitossanidade']});

	$(".date-picker").datepicker();
	
});
</script>

{% endblock extra_js %}